apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: covid19estimator 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: covid19estimator 
    spec:
      containers:
        - name: covid19estimator 
          image: covid19reg.azurecr.io/covid19estimator
          env:
            - name: CUSTOMCONNSTR_covid_db_conn
              valueFrom:
                secretKeyRef:
                  name: covidsecrets
                  key: db_conn
            - name: DATABASE_ID
              valueFrom:
                secretKeyRef:
                  name: covidsecrets
                  key: database
            - name: CONTAINER
              valueFrom:
                secretKeyRef:
                  name: covidsecrets
                  key: container
          ports:
          - containerPort: 8080